name: 02 - workflow Events
on: push

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: show the trigger
              run: echo "I am triggered by ${{github.event_name}}"