name: 03 - Workflow Runers
on: workflow_dispatch
jobs: 
    ubuntu-echo:
        runs-on: ubuntu-latest
        steps: 
            - name: Show OS
              run: |
                echo "This job is running in ubuntu"
                echo "Runner OS: $RUNNER_OS"
    windows-hello:
        runs-on: windows-latest
        steps:
            - name: Show OS
              shell: bash
              run: | 
                echo "This job is running on windows"
                echo "Runner OS: $RUNNER_OS"
    macos-hello:
        runs-on: macos-latest
        steps:
            - name: Show OS
              run: | 
                echo "This job is running on macos"
                echo "Runner OS: $RUNNER_OS"    


