name: 04 Actions
on: 
    push:
jobs: 
    build:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Prinding Folders
              run: ls
            - name: setup node
              uses: actions/setup-node@v3
              with:
                node-version: '20.x'
            - name: Installing dependencies
              run: npm ci
              working-directory: ./react-app

