name: 05 Event filters and activity types
on:
    pull_request:
        types:
            - opened
            - synchronize
        branches:
            - main
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: run1
              run: echo "Running whrn PR is opeped ans synchronized"
            


